development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: patchwork_development
  username: patchwork
  password: passw0rd

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: patchwork_test
  username: patchwork
  password: passw0rd

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: patchwork_production
  username: patchwork
  password: passw0rd
